language: node_js
node_js: node
services: 
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AJumbDGCHkAZfw3xgX9hBHbdx19AtV/vjk67DcBRrIipW8u3ZEzOc0V5D7I4MofH3R82s3vbT8rvitugALISWKu0m3w/aVGBvmTl04PyGccOlMKEUsjyYPmyvNHAtp1ase7o9HHQzCfvaWJxl95ytwwfhGUN6KQyOmjxHQBgvUqzQ210xEZVJa894LoNHgrMr49oGrWANZfmEaSfwyopUqqGlHuW8qIPKf6I0JBUVSOMVD+EfCz4DTCvGnHwoK3zCHWoWB3eH6sPQjmfWW0ptnqc+PLAXIrpt8oSlBz+CVCn9vbNjRKi9tfLpI3J/JvA7XlgxVh0VMsiNL6ZN7IVkT2YedTmpWFjIstDafdgB5Axj1vtkYS4JPFrNOTNgUTfF905EGMg0ZrdsxHels4u+t5CItVVeT691SH5pkjLfNo+5O7nKR7WxntgyOs8PzJ3cLtlA5IWXrmWVhaOAGOQu810QC/vM295K26Dfg+Vh6R+INKycdyS52fcZEK36fYO1a44qQJoLmLgbdnzGp+XkQUVxtZFV3N4w04LN7zgs2PvTmuS6f5U6OKjLJksYwNFl3mV64U4WHobqmI9qK4aZ/2ys6sf919irMLNW64GNRCrxOWAnDxDy7woyjDem8ai/f+IYFk9QNgJKxABTI+h0R7gqpeAuR1FA1WvlulmqjY=
  app: mighty-escarpment-83989
  on:
    repo: GilliganL/tailored-knits-api2
